### ISSUE TITLE
mod suggestion

### ISSUE THREAD

**Issue by Atroxil** [GreatOrator/FallCraft#10]
Just a suggestion, but especially with all the new status effects I am thinking it might be really nice to have a little more information in the UI about what our armor status is at, and I like to see what effects are on me sooner rather than in the inventory screen.  To this effect, I propose adding:
bspkrs' mods (ArmorStatusHUD and StatusEffectHUD). 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1282347-bspkrs-mods-armorstatushud-directionhud
Their directionHud is nice but not needed with a map mod.

**Comment by GreatOrator** [comment]
Yeah, that is a choice I am considering.  Bspkrs are one option, also consider rpgHUD again or Damage Indicators as the last two also offer some customizable options bspkrs does not.  Just had not determined which one yet until I see what kind of screen realestate the existing mods take up

**Comment by Atroxil** [comment]
I personally didn't care for rpgHud for a couple of reasons. 1. the portrait in the corner was huge and unnecessary and its other options to hide said portrait didn't help. 2. It doesn't work with charged armor - so redstone arsenal and draconic armor were all shown as broken even at full charge. I'm also not sure how it interacts with IC2 armor.

**Comment by GreatOrator** [comment]
So looking over all of the options for additional HUD information, just how important is it to have your armor, status effects, etc show up in the main screen?  As I look at what's available and consider some of the discussions I have had using them in Tolkiencraft, I am actually leaning towards not having them in this pack at all.

**Comment by WildStarorion** [comment]
Another Mod suggestion

Modular Power suits
http://minecraft-forum.net/minecraft-mods-downloads/1-5-2-modular-powersuits-mod-download-2-2/#.Vcirc_lVhBc

I think this might fit in well with your space themed idea

**Comment by GreatOrator** [comment]
Actually -http://minecraft.curseforge.com/mc-mods/224011-modular-armour already have it in there :)

**Comment by WildStarorion** [comment]
doh how did i miss that :)

**Comment by GreatOrator** [comment]
Modular armor currently has a bug that is causing a crash on startup so has been temporarily removed.  I have reported to the mod dev, but have not heard back yet.

**Comment by GreatOrator** [comment]
So the power suits are back in, and seem to be working fine now, so closing issue.
