### ISSUE TITLE
agricraft seeds dissappearing

### ISSUE THREAD

**Issue by birdiegirl** [GreatOrator/FallCraft#15]
set the stage.. we have a 222 seed in inventory, we have a 333 seed on the hotbar.  we want to place the 333 by right clicking.  what happens is, we hear the pop when our inventory is moving the 222 seed  to our hotbar, but, the 222 seed disappears.    it is not just invisible, it disappears.

**Comment by GreatOrator** [comment]
There seems to be a number of issues with inventory tweaks, this, the inability to shift click into inventory, etc.  I am going to test though as I seem to think it is a mod conflict for keybindings

**Comment by GreatOrator** [comment]
Let's try this on the new build.  Some of the other inventory issues seem to have been resolved by removing galacticraft.

**Comment by birdiegirl** [comment]
ok GO,  if we right click sugar cane to harvest   it puts the sugar cane in our hand.  if we right click to harvest the next one,  it DISAPPEARS.  so, both morvash and I have had this happen.  so basically, when we have the item in our hand and want to right click to harvest , it does not harvest the next one.

**Comment by birdiegirl** [comment]
ok, further,  it shows the crop as harvested but it does not put the harvested item in your back pack or hand or ground

**Comment by InfinityRaider** [comment]
This was a bug when I implemented direct planting of sugarcane onto crop sticks.
It would plant the sugarcane, even if there was already a plant there. So it looked like the harvesting didn't do anything.
This will be fixed in the next build of Agricraft

**Comment by GreatOrator** [comment]
Can someone confirm if they are still seeing this issue after the latest update?

**Comment by birdiegirl** [comment]
GO, sorry I did not reply sooner  just saw this email.  Morvash and I have not had this problem happen since the update
Lisa 


     On Sunday, September 20, 2015 5:51 AM, GreatOrator <notifications@github.com> wrote:
   

 Can someone confirm if they are still seeing this issue after the latest update?—

**Comment by GreatOrator** [comment]
Excellent, will close this out then.  Off-topic, don't forget to accept the invite to the group on player.me :)

**Comment by birdiegirl** [comment]
I was already part of TC on player just went and joined the group for fallcraft today 

 


     On Monday, September 21, 2015 10:05 AM, GreatOrator <notifications@github.com> wrote:
   

 Excellent, will close this out then. Off-topic, don't forget to accept the invite to the group on player.me :)—
