### ISSUE TITLE
ancient warfare tree growing

### ISSUE THREAD

**Issue by birdiegirl** [GreatOrator/FallCraft#24]
I have yellow 1 autumn sapling in spot one, 4 orange autumn sapling in spot two, and 52spruce wood saplings in spot three.. ancient warfare will only plant the first item listed. it will ignore the 2nd and 3rd tree saplings i Have

**Comment by GreatOrator** [comment]
Will take a look and report it, may have to do with modded trees maybe?

**Comment by GreatOrator** [comment]
Can we confirm if the latest update fixed this issue?
