### ISSUE TITLE
New spawn point is in the ground

### ISSUE THREAD

**Issue by birdiegirl** [GreatOrator/FallCraft#36]
Hey GO,   when Morvash and I logged in after updating to .3, we were put in the ground.  luckily we had our picks and were able to get out without dying but new worlds may not be as nice :)

**Comment by GreatOrator** [comment]
Same as closed issue

https://github.com/GreatOrator/FallCraft/issues/34

This is because the spawn point is marked for the default map which is not yet available for testing.  Plans are to have a working map for testers as soon as possible.
