### ISSUE TITLE
Can we get a map updating feature in Fallcraft, too?

### ISSUE THREAD

**Issue by nickseo7** [GreatOrator/FallCraft#58]
## Description
Tolkiencraft III(Mad Help 1.10.2) has that feature for the new update, and since Fallcraft is also updating currently, I think it would be great for players to save their progress after the update(s).
## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: 10.13.4.1566
* FallCraft version:

## Crash report
```
CRASH REPORT HERE
```

**Comment by GreatOrator** [comment]
It actually already does, there is a download link for the map on the main menu and I update the configs to reflect when there are map changes.  Now, if it is not working correctly, that is a different story but the feature is there.  I just put it on curse as an extra way to get the map.

**Comment by nickseo7** [comment]
Oops, word selection. I was talking about the Regional Download feature in Tolkiencraft III, not the update notices.

**Comment by GreatOrator** [comment]
Well, unlike TC3, fallcraft is just one map where TC3 has separate dimension for play.  That's why FallCraft only has a single download link

**Comment by nickseo7** [comment]
Wait, I think I mistook what you replied then. Because when I downloaded the map for the update before, it just created another world file, not updating an existing file.

**Comment by nickseo7** [comment]
Yep. So that it's able to keep the progress.
If the latest map is fully updated one, it would not be a problem, though.

**Comment by GreatOrator** [comment]
Alright, I can look into that, it's actually something easy to implement, look for it within the next update as an option.

**Comment by nickseo7** [comment]
Thank you!

**Comment by GreatOrator** [comment]
Welp, with the most recent full release I added it. Enjoy!
